a) Create numpy nd array and a normal list print their types:

In [274]:
AnArray=np.array([1,2,3,4])
print (AnArray)
print (type(AnArray))

[1 2 3 4]
<class 'numpy.ndarray'>


In [275]:
List=['Pink','Violet','Purple','Red']
print (List)
print(type(List))

['Pink', 'Violet', 'Purple', 'Red']
<class 'list'>


b) Create a data pandas frame with 3 columns:

In [276]:
a={'First Name':['Sanyuja','Siddarth','Gourang','Sujan','Pavan'],
   'Last Name':['Desai','Marathe','Amrujkar','Srinivas','Rajashekar'],
   'Team Name': ['Game of python','Game of python','Game of python','Game of python','Game of python']}
Dataset=pd.DataFrame(a,columns=['First Name','Last Name','Team Name'])
Dataset

First Name   Last Name       Team Name
0    Sanyuja       Desai  Game of python
1   Siddarth     Marathe  Game of python
2    Gourang    Amrujkar  Game of python
3      Sujan    Srinivas  Game of python
4      Pavan  Rajashekar  Game of python

c)create a data frame with random integers with column ABCD and rows XYWZP

In [277]:
Rows=['X','Y','W','Z','P']
Columns=['A','B','C','D']
RandIntg= pd.DataFrame(np.random.randn(5, 4),index=Rows, columns=Columns)
RandIntg

A         B         C         D
X  0.501753 -0.469195  0.755821  1.608772
Y  0.591961  0.635619 -0.161773  0.574101
W  0.474486  0.440095 -0.050283 -0.946159
Z  1.416210  0.934059 -0.213746  1.197739
P  0.967244  1.844734  0.806336  0.760016

d) Initialize a 1 D numpy array with duplicate elements like 1,2,3,1,2,3 and print the list of unique elemnents


In [278]:
oneD=np.unique([1,2,3,1,1,3,3,2,2])
print(oneD)

[1 2 3]


Import Titanic dataset as numpy array:

In [279]:
import numpy as np
import pandas as pd

In [280]:
titanic=pd.read_csv('titanic dataset.csv')
X=titanic.values
y=titanic['PassengerId']
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

e) Use query fucntion and retreive on the condition Sex is male[Titanic Data Set]

In [281]:
Male=titanic.loc[(data["Sex"]=="male")]
Male[0:7]

PassengerId  Survived  Pclass                            Name   Sex   Age  \
0             1         0       3         Braund, Mr. Owen Harris  male  22.0   
4             5         0       3        Allen, Mr. William Henry  male  35.0   
5             6         0       3                Moran, Mr. James  male   NaN   
6             7         0       1         McCarthy, Mr. Timothy J  male  54.0   
7             8         0       3  Palsson, Master. Gosta Leonard  male   2.0   
12           13         0       3  Saundercock, Mr. William Henry  male  20.0   
13           14         0       3     Andersson, Mr. Anders Johan  male  39.0   

    SibSp  Parch     Ticket     Fare Cabin Embarked  
0       1      0  A/5 21171   7.2500   NaN        S  
4       0      0     373450   8.0500   NaN        S  
5       0      0     330877   8.4583   NaN        Q  
6       0      0      17463  51.8625   E46        S  
7       3      1     349909  21.0750   NaN        S  
12      0      0  A/5. 2151   8.0500   NaN        S  
13      1      5     347082  31.2750   NaN        S

f) Use query fuction and retreive on the condition Sex is female and age > 30

In [282]:
Female30=titanic.loc[(data["Sex"]=="female") & (data["Age"] > 30)]
Female30[0:5]

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
11           12         1       1   
15           16         1       2   
18           19         0       3   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
11      0    113783  26.5500  C103        S  
15      0    248706  16.0000   NaN        S  
18      0    345763  18.0000   NaN        S

g) Use the apply function on age column to decrease age of every row by 2 and print column

In [283]:
sub2=titanic["Age"]-2
sub2[0:4]

0    20.0
1    36.0
2    24.0
3    33.0
Name: Age, dtype: float64

h) Use groupby function in pandas to group by sex column.Iterate and print the group [Titanic]

In [284]:
Sex=titanic.groupby(["Sex"]).count()
SibSp=titanic.groupby(["SibSp"]).count()
Embarked=titanic.groupby(["Embarked"]).count()
print('--------Sex Count---------\n',Sex)
print('---------SibSp Count----------\n',SibSp)
print('--------Embarked Count--------\n',Embarked)

--------Sex Count---------
         PassengerId  Survived  Pclass  Name  Age  SibSp  Parch  Ticket  Fare  \
Sex                                                                            
female          314       314     314   314  261    314    314     314   314   
male            577       577     577   577  453    577    577     577   577   

        Cabin  Embarked  
Sex                      
female     97       312  
male      107       577  
---------SibSp Count----------
        PassengerId  Survived  Pclass  Name  Sex  Age  Parch  Ticket  Fare  \
SibSp                                                                       
0              608       608     608   608  608  471    608     608   608   
1              209       209     209   209  209  183    209     209   209   
2               28        28      28    28   28   25     28      28    28   
3               16        16      16    16   16   12     16      16    16   
4               18        18      18    18   18   18 

i) intialize a 3x3 numpy array with values of your choice,print it and print sum along the rows and columns.

In [285]:
Mychoice=[[1,2,3,],[5,6,7],[8,9,10]]
Mychoice=np.array(Mychoice)
print("Matrix:\n",Mychoice.reshape(3,3))
print("Sum of Columns:\n",Mychoice.sum(axis=0))
print("Sum of rows:\n",Mychoice.sum(axis=1))

Matrix:
 [[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
Sum of Columns:
 [14 17 20]
Sum of rows:
 [ 6 18 27]


j) initialize a 3x3 numpy array and flatten it

In [286]:
print("Original Matrix:\n",Mychoice)
print("Flattened matrix:\n",Mychoice.flatten())

Original Matrix:
 [[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
Flattened matrix:
 [ 1  2  3  5  6  7  8  9 10]


k) Use the lamba function and add 2 years to the age column from every record.[Titanic]

In [287]:
#Solution With numpy:
W=np.array(titanic["Age"])
scale= lambda x: x+2
print (W)
print(scale(W))

[ 22.    38.    26.    35.    35.      nan  54.     2.    27.    14.     4.
  58.    20.    39.    14.    55.     2.      nan  31.      nan  35.    34.
  15.    28.     8.    38.      nan  19.      nan    nan  40.      nan
    nan  66.    28.    42.      nan  21.    18.    14.    40.    27.      nan
   3.    19.      nan    nan    nan    nan  18.     7.    21.    49.    29.
  65.      nan  21.    28.5    5.    11.    22.    38.    45.     4.      nan
    nan  29.    19.    17.    26.    32.    16.    21.    26.    32.    25.
    nan    nan   0.83  30.    22.    29.      nan  28.    17.    33.    16.
    nan  23.    24.    29.    20.    46.    26.    59.      nan  71.    23.
  34.    34.    28.      nan  21.    33.    37.    28.    21.      nan  38.
    nan  47.    14.5   22.    20.    17.    21.    70.5   29.    24.     2.
  21.      nan  32.5   32.5   54.    12.      nan  24.      nan  45.    33.
  20.    47.    29.    25.    23.    19.    37.    16.    24.      nan  22.
  24.    19. 

In [288]:
#Solution with pandas:
Age2=titanic['Age'].apply(lambda x:x+2)
print('original:\n',titanic["Age"])
print('Age plus two:\n',Age2)


original:
 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
Age plus two:
 0      24.0
1      40.0
2      28.0
3      37.0
4      37.0
5       NaN
6      56.0
7       4.0
8      29.0
9      16.0
10      6.0
11     60.0
12     22.0
13     41.0
14     16.0
15     57.0
16      4.0